### ISSUE TITLE
Total precache size is about 0 B for 0 resources. 

### ISSUE THREAD

**Issue by OrangeXC** [hanford/next-offline#1]
# Expected Behavior

The `next-offline` should precache all .next folder's ressources?

# Current Behavior

Cache nothing.

Steps to Reproduce (for bugs)

* Do install same README document
* Run npm build

The result is:

> Using "webpack" config function defined in next.config.js.
> Total precache size is about 0 B for 0 resources.

# Context

I would like to use `next-offline` with NextJS

# My Environment

Tech | Version
-- | --
next | 5.0.0
React | 16.2
node | 8.9.4
OS | MacOSX
browser | Chrome
etc

**Comment by hanford** [comment]
Thanks for the issue @OrangeXC!

I believe that is because the default caching strategy is `networkFirst` which means by default the service worker will try to hit the network to load assets, and will only fall back to the cache if the network request fails. The image below describes it well

![35582735-7b5f970e-05a4-11e8-8397-ea8e69c7fa1d](https://user-images.githubusercontent.com/2148168/36041355-16d6b62e-0d7d-11e8-9f0a-404edb2922f9.png)

You can play around with different handlers by using passing in a `swPreCacheOptions` object

Additionally you can read more about these handlers [in some of googles documentation](https://googlechromelabs.github.io/sw-toolbox/api.html#handlers) - all `next-offline` is, is an abstraction over `sw-precache-loader` which is an abstraction over googles `sw-precache` which under the hood is using `sw-toolbox` (crazy, right?)

I'm using `next-offline` on my personal website, if you go to [https://jackhanford.com](https://jackhanford.com) and look at the network tab you'll see that all requests are going through the service worker, you can also simulate offline and reload the page and the service worker cache works as expected (everything loads!) ... If that's helpful you can also look at all of the code for my website which is [in this repo](https://github.com/hanford/personal-website)

**Comment by hanford** [comment]
closing in favor of #3
