### ISSUE TITLE
Question? (sorry for posting as issue :( )

### ISSUE THREAD

**Issue by pkellner** [hanford/next-offline#116]
You did say in your article questions, feel free to post here.

I've got next-offline working with now1 and am confused on where I need to go to add REST GET call offline support. That is, when the app first loads I want it to store some static json files, and then if it goes offline, I want it to use those (and occassionally refresh). I gather I need to somehow updated my service-worker.js file with events but am lost. You generate that service-work for me and I just included it in my express script serving.

Hints?  -thanks

**Comment by hanford** [comment]
@pkellner so that is where [workbox](https://developers.google.com/web/tools/workbox/) comes in, basically you can pass in various different options through next-offline that will help configure workbox, which is what next-offline uses under the hood.

Workbox will automatically record network requests and store them in IndexDB on the frontend, if the request can't be fulfilled (no network) it will try to find a cached response.

You can find out about the cache strategies that workbox supports in this blog post: https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/

**Comment by pkellner** [comment]
Thanks so much.
