### ISSUE TITLE
now2 example SW Registration Failed

### ISSUE THREAD

**Issue by charlie632** [hanford/next-offline#131]
I downloaded the _now2_ example from the repo, npm installed, and then ran the example. I got the following error: 

`SW registration failed:  TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.`

I tried building the app and running it with a production environment. Below is my package json.

```json
{
  "name": "create-next-example-app",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "cross-env NODE_ENV=production next start"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "next": "^7.0.2",
    "next-offline": "latest",
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  }
}

```

Same error as above.

**Comment by hanford** [comment]
the now 2.0 example relies on the `now.json` being used (that's what actually tells Now what to do when a request for the SW comes in) .. which only happens when the application is being hosted on now 2.0.

I bet if you typed `now` and deployed the application it would work as expected. Going to close this because i don't think this is an issue specific to next-offline
