### ISSUE TITLE
better next export support

### ISSUE THREAD

**Issue by hanford** [hanford/next-offline#23]
currently `next-offline` only works with `next export` when the user has an `exportPathMap` `Next@6.0.0` now will generate the path map if the user doesn't declare one and `next-offline` should support that use case.

**Comment by joaovieira** [comment]
@hanford that export is also not compatible with Next apps on a custom `dir` (e.g. `/app` instead of `.`) and/or with a custom `distDir` (e.g. `/build` instead of `/.next`) as it's assuming everything will be built under `$projectRoot/.next`. Don't know if that's a known issue and if you want to bundle in here.

**Comment by hanford** [comment]
@joaovieira can you move that to a new issue? That should very easy to support :)

**Comment by hanford** [comment]
https://github.com/zeit/next.js/pull/5089

should simplify!
