### ISSUE TITLE
express custom server + next-routes example? getting unsupported mime type

### ISSUE THREAD

**Issue by brad-decker** [hanford/next-offline#55]
i'm using next routes and express. next-routes creates a custom handler that up until installed next-offline i just used as an express middleware. When i attempt to do the following:

```js
  server.use((request, response) => {
    const parsedUrl = parse(request.url, true);
    const { pathname } = parsedUrl;
    if (pathname === '/service-worker.js') {
      const filePath = join(__dirname, '.next', pathname);

      return app.serveStatic(request, response, filePath);
    }

    return handler(request, response, pathname);
  });
```

The error i receive in console is this;

```
SW registration failed:  DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').
```

I am using next 7 canary 11 right now, so this could just be an artifact of that. Thanks!

**Comment by hanford** [comment]
@brad-decker I haven't used `next-routes` really so that could be the culprit. Also haven't looked at Next 7 much yet so that could also be a problem.

I think the mime type error is actually a 404. Can you provide a link where this is occurring? 

does going to your `https://your-server.com/service-worker.js` result in a redirect or 404?

Could your try and get a repo with the bare code  to reproduce? Thanks!

**Comment by hanford** [comment]
thanks @alexanbj!

Going to close this until we get some additional info @brad-decker, if you come back with some specifics I'd be happy to reopen!
