### ISSUE TITLE
Add workbox-range-request for video files

### ISSUE THREAD

**Issue by xcv58** [hanford/next-offline#77]
Video can't play in iOS devices since.

We can add workbox-range-request plugin to solve the problem. I think it worth to add as default rules.

More details in: https://github.com/nuxt-community/pwa-module/issues/64#issuecomment-422324895

**Comment by hanford** [comment]
@xcv58 thanks for opening, otherwise i would have likely had to figure out what was going on if someone else asked about this issue.

However - I don't want to make assumptions about other peoples setups, so I'm sort of against adding more options on the `next-offline` user's behalf.

I'd love if you opened a PR or something and added a trouble shooting section to the README calling out that video might be broken without a `workbox-range-request`.

Thanks again!

**Comment by xcv58** [comment]
The fixed example: https://github.com/xcv58/next-offline-issue-77/pull/1/files

**Comment by xcv58** [comment]
The video can't be served through service worker at all because:

https://github.com/GoogleChrome/workbox/issues/1663
