### ISSUE TITLE
Usage with @now/next on Now 2.0

### ISSUE THREAD

**Issue by 4cm4k1** [hanford/next-offline#90]
# Question/Discussion

I'm fairly close to being done preparing my project to use `@now/next` on Zeit's Now 2.0, instead of a Dockerized custom server on Now 1.0. But some issues remain.

1. One issue is, as we know, although `next-offline` outputs `service-worker.js` to `.next`, a custom server is required to serve the file. Also, while the `@now/next` builder does output `service-worker.js` to `.next` in the Now 2.0 environment, it ultimately does not end up in the generated `_next` path (e.g., look [here](https://zeit.co/acm4k1/anthony-codes/7gau039xh/source) and click on `_next` to see it's not there).
2. Another issue is that the `@now/next` builder purposefully does not have access to `static/**/*`, which results in none of those assets being added to the precache manifest, as alluded to in this warning:
```shell
WARNING One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": ".",
  "globPattern": "static/**/*",
  "globIgnores": [
    "**/node_modules/**/*"
  ]
}
```
I'm curious what the community thinks would be the best solution for making `next-offline` work with Zeit's new architecture. Any ideas?

**Comment by 4cm4k1** [comment]
One easy route to making it work would be to use `@now/static-build` with `next export`, but the downside would be losing the ability to have runtime `getInitialProps`.

**Comment by hanford** [comment]
@4cm4k1 I've talked a little bit with Tim who is one of the maintainers of Next.js. He mentioned they'll be rolling out some things that we'll be able to use to make sure `next-offline` works with Zeit's Now 2.0

Specifically allowing plugins to hook into the new next build mode (`next build --lambdas`)

I'm currently working on migrating one of my other [personal projects](https://github.com/hanford/trends/tree/now2) to Now 2.0, but ran into some snags that are blocking me a little bit.

https://spectrum.chat/?thread=604f6aa6-23f2-4358-8b0b-14e5810178dc
https://spectrum.chat/notifications?thread=5024fde9-05d2-4897-a425-4416c47d96c8

**Comment by hanford** [comment]
I was able to get next-offline working without any changes on Now 2.0!

I'm planning on doing a pretty big overhaul of the next-offline documentation in the next week or so where I can go into the differences I've noticed between Now 1.0 and 2.0 and the different things to be aware of.

If you'd like to start using it before then, you can check out this project: https://github.com/hanford/trends/pull/12 and these lines specifically

[Service Worker Allowed Header](https://github.com/hanford/trends/pull/12/files#diff-96c813af76efae3c872399365c060e54R19)
[Service Worker Scoping](https://github.com/hanford/trends/pull/12/files#diff-036b832895f0e34286b4f9ac3b59b509R93)

Where because we can no longer serve the Sw from the root directory (foobar.com/service-worker) we need to add a new header to served SW allowing it to work outside of it's scope.

The header I added is applied to all assets in that project, that'll likely need to be fixed but I've been running into strange Now 2.0 related (behavior? bugs?) that prevented it

**Comment by 4cm4k1** [comment]
Awesome news! Do you have assets in `www/static/` though for your Trends project? If there are some, they're still not getting to the `sw.js`: https://trends.now.sh/_next/static/sw.js

**Comment by 4cm4k1** [comment]
Also, I wanted my static assets to load from the root (because `keybase.txt` requires it, and I wanted to preserve the same link for my résumé file), so I put this in `routes` in `now.json`:
```json
{

"src": "^/(.*)[.](html|ico|jpg|json|pdf|png|svg|txt|webp|xml)$",

"headers": {

"Cache-Control": "public, max-age=31536000, immutable"

},

"dest": "/static/$1.$2"

}
```
Couldn't one apply the same technique to load `sw.js` from root and stick with autoregistering it?

**Comment by hanford** [comment]
1). Ahh didn't notice that! The trends project doesn't really have assets, but it does have a lot of favicons and such that should probably be in the SW 🙇‍♂️ which presents an interesting dilemma because i don't think `@now/static` stuff goes through webpack meaning next-offline wouldn't never know (at compile time) about them. However - Workbox should correctly cache and handle @ runtime

2). I think you're right, I could probably do that. I was having some strange issues that lead me to getting a hack to work. I'll do another pass at some point and clean it up. In the case of trends, there actually is only 15ish lines of JS that the client uses (react and all dependencies are omitted clientside) so it couldn't auto register regardless.

I'll be converting a more real life project to Now 2.0 ([my personal website](https://github.com/hanford/personal-website)!) and that should give me a good idea of what could be not working or is straight up broken.

I really appreciate the back and forth btw! 🙏

**Comment by 4cm4k1** [comment]
Given we've found a solution and you added an example and documentation for Now 2.0, I'll close this issue. Thanks again!
